# -*- coding: utf-8 -*-
"""Punto_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyLPKr76XsXXICfinr2kBoVhA43Up0iB

# **Quinto Punto**

**Enunciado:** Imprimir el factorial de un número natural n dado.
"""

n = int(input("Ingrese un número natural:"))
factorial = 1

while n > 0:
  factorial *= n
  n -= 1

print("El factorial del número es: " + str(factorial))